services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir ./app --reload-dir ./misc
    volumes:
      - ./backend:/app
  
  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass senharedis
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local
